package com.livraria.exception;

import org.springframework.http.HttpStatus;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum TabelaDeErros {
	
	VALIDACAO (HttpStatus.BAD_REQUEST ,"1000 - 1000", "DADOS DE REQUISIÇÃO INVÁLIDOS, TENTE NOVAMENTE"),
	
	CLIENTE_NAO_ENCONTRADO (HttpStatus.NOT_FOUND,"1000 - 3001", "INFORMAÇÕES INVÁLIDAS, CLIENTE NÃO ENCONTRADO"),
	LIVRO_NAO_ENCONTRADO (HttpStatus.NOT_FOUND,"1000 - 3001", "INFORMAÇÕES INVÁLIDAS, LIVRO NÃO ENCONTRADO"),
	ENDERECO_NAO_ENCONTRADO (HttpStatus.NOT_FOUND,"1000 - 3001", "INFORMAÇÕES INVÁLIDAS, ENDEREÇO NÃO ENCONTRADO"),
	TELEFONE_NAO_ENCONTRADO (HttpStatus.NOT_FOUND,"1000 - 3001", "INFORMAÇÕES INVÁLIDAS, TELEFONE NÃO ENCONTRADO"),
	CARRINHO_NAO_ENCONTRADO (HttpStatus.NOT_FOUND,"1000 - 3001", "INFORMAÇÕES INVÁLIDAS, CARRINHO NÃO ENCONTRADO"),
	COMPRA_NAO_ENCONTRADA (HttpStatus.NOT_FOUND,"1000 - 3001", "INFORMAÇÕES INVÁLIDAS, COMPRA NÃO ENCONTRADA"),
	
	ENDERECO_CINCULADO_A_CLIENTE(HttpStatus.CONFLICT, "1000 - 2002", "ENDEREÇO VINCULADO A UM CLIENTE"),
	COMPRA_CINCULADA_A_CLIENTE(HttpStatus.CONFLICT, "1000 - 2002", "COMPRA VINCULADA A UM CLIENTE"),
	CPF_JA_CADASTRADO (HttpStatus.CONFLICT ,"1000 - 4009", "O CPF JÁ CONSTA NA BASE DE DADOS"),
	LIVRO_JA_CADASTRADO (HttpStatus.CONFLICT ,"1000 - 4009", "ESSE LIVRO JÁ CONSTA NA BASE DE DADOS"),
	ENDERECO_JA_CADASTRADO (HttpStatus.CONFLICT ,"1000 - 4009", "O ENDEREÇO JÁ CONSTA NA BASE DE DADOS"),
	TELEFONE_JA_CADASTRADO (HttpStatus.CONFLICT ,"1000 - 4009", "ESSE NÚMERO JÁ CONSTA NA BASE DE DADOS"),
	
	SISTEMA(HttpStatus.INTERNAL_SERVER_ERROR,"1000 - 5000", "SISTEMA INDISPONÍVEL, TENTE MAIS TARDE");

	private final HttpStatus codigoHttp;
	private final String codigoErro;
	private final String mensagem;
	

}
